name: update Dynv6 A

on:
  schedule:
    - cron: '30 03 * * 1' # 周一早三点半运行
  workflow_dispatch: # 允许手动触发

jobs:

  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 4
        
    - name: Run script 
      env:
        DYNV6_TOKEN: ${{ secrets.DYNV6_TOKEN }}
        QQ_771_TOKEN: ${{ secrets.QQ_771_TOKEN }}
        DYNU_TOKEN: ${{ secrets.DYNU_TOKEN }}
        LIVE_F02_TOKEN: ${{ secrets.LIVE_F02_TOKEN }}
        LIVE_CFV_TOKEN: ${{ secrets.LIVE_CFV_TOKEN }}
        LJK_E37_TOKEN: ${{ secrets.LJK_E37_TOKEN }}
        LJK_E37_003: ${{ secrets.LJK_E37_003 }}
      run: |
        python ${{ github.workspace }}/Dynv6.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        if [ -n "$(git status --porcelain)" ]; then
          git add index.html
          git commit -m "Automatic update"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
