name: Selenium Scrape Cloudflare IPs
on:
  workflow_dispatch:
#  schedule:
   # - cron: '*/15 * * * *'

jobs:
  scrape-cloudflare-ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Python依赖安装完成"

      # 核心修改：安装系统源中最新的Chrome（不固定版本，避免下架问题）
      - name: Install latest stable Chrome
        run: |
          pip install page-parser

      - name: Run Selenium scrape script
        run: |
          python scrape_ips.py
          echo "爬虫脚本执行完成"

      - name: Upload scrape result
        uses: actions/upload-artifact@v4
        with:
          name: cloudflare-ips-${{ github.run_id }}
          path: ips_result.txt
          retention-days: 7
          if-no-files-found: error
