name: Selenium Scrape Cloudflare IPs
on:
  workflow_dispatch:
 # schedule:
  #  - cron: '*/15 * * * *'

jobs:
  scrape-cloudflare-ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip show selenium chromedriver-binary
          echo "Python依赖安装完成"

      # 核心修改：更换为源中可获取的Chrome版本（128.0.6613.138-1）
      - name: Install fixed-version Chrome browser
        run: |
          # 卸载旧版Chromium
          sudo apt-get remove -y chromium-browser chromium-browser-l10n chromium-codecs-ffmpeg
          sudo apt-get autoremove -y
          # 添加Chrome官方源
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update -y
          # 安装当前可获取的稳定版本（128.0.6613.138-1，已验证源中存在）
          sudo apt-get install -y google-chrome-stable=128.0.6613.138-1
          # 验证版本
          google-chrome --version
          echo "Chrome浏览器安装完成（版本：128.0.6613.138）"

      - name: Run Selenium scrape script
        run: |
          python scrape_ips.py
          echo "爬虫脚本执行完成"

      - name: Upload scrape result
        uses: actions/upload-artifact@v4
        with:
          name: cloudflare-ips-${{ github.run_id }}
          path: ips_result.txt
          retention-days: 7
          if-no-files-found: error
